### ISSUE TITLE
Rate Limit Exceeded on chat message send

### ISSUE THREAD

**Issue by ledlamp** [skyware-js/bot#12]
Thought this library was supposed to handle rate limits but I got "Failed to send message(s)." errors after using bot.sendMessages() a bunch of times.

```
Error: Failed to send message.
    at file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:971:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.sendMessage (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:959:26)
    at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:42:3) {
  [cause]: XRPCError: RateLimitExceeded > Rate Limit Exceeded
      at RateLimitedAgent.request (file:///home/ubuntu/bskychatbot/node_modules/@atcute/client/dist/rpc.js:82:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Bot.sendMessage (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:959:26)
      at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:42:3) {
    status: 429,
    kind: 'RateLimitExceeded',
    description: 'Rate Limit Exceeded',
    headers: {
      'access-control-allow-origin': '*',
      'cache-control': 'private',
      'content-length': '61',
      'content-type': 'application/json; charset=utf-8',
      date: 'Fri, 25 Oct 2024 20:59:10 GMT',
      etag: 'W/"3d-egyFOcXCrKQFzoI7522/4+PpxIk"',
      'keep-alive': 'timeout=90',
      'ratelimit-limit': '3000',
      'ratelimit-policy': '3000;w=300',
      'ratelimit-remaining': '2902',
      'ratelimit-reset': '1729889985',
      'strict-transport-security': 'max-age=63072000',
      vary: 'Authorization, Accept-Encoding',
      'x-powered-by': 'Express'
    },
    [cause]: undefined
  }
}
```

**Comment by futurGH** [comment]
Are you on 0.3.6? I fixed some ratelimit-related issues in the latest update. If not, try updating and let me know if you still run into this.

**Comment by ledlamp** [comment]
Yes, it is 0.3.6.

**Comment by futurGH** [comment]
Got it, can you try 0.3.7-beta.0 and see if this continues to happen?

**Comment by ledlamp** [comment]
It looks like it happened again, but error.stack doesn't include cause, next time will log Error object

![image](https://github.com/user-attachments/assets/48fc4f40-6e62-44ab-90d8-e232a9054a12)

**Comment by ledlamp** [comment]
```
Error: Failed to send messages.
    at file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1019:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.sendMessages (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1016:26)
    at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:61:3) {
  [cause]: XRPCError: RateLimitExceeded > Rate Limit Exceeded
      at RateLimitedAgent.request (file:///home/ubuntu/bskychatbot/node_modules/@atcute/client/dist/rpc.js:82:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Bot.sendMessages (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1016:26)
      at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:61:3) {
    status: 429,
    kind: 'RateLimitExceeded',
    description: 'Rate Limit Exceeded',
    headers: {
      'access-control-allow-origin': '*',
      'cache-control': 'private',
      'content-length': '61',
      'content-type': 'application/json; charset=utf-8',
      date: 'Sat, 26 Oct 2024 04:06:11 GMT',
      etag: 'W/"3d-egyFOcXCrKQFzoI7522/4+PpxIk"', 
      'keep-alive': 'timeout=90',
      'ratelimit-limit': '3000',
      'ratelimit-policy': '3000;w=300',
      'ratelimit-remaining': '2995',
      'ratelimit-reset': '1729915865',
      'strict-transport-security': 'max-age=63072000',
      vary: 'Authorization, Accept-Encoding',
      'x-powered-by': 'Express'
    },
    [cause]: undefined
  }
}
Error: Failed to send messages.
    at file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1019:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.sendMessages (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1016:26)
    at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:61:3) {
  [cause]: XRPCError: RateLimitExceeded > Rate Limit Exceeded
      at RateLimitedAgent.request (file:///home/ubuntu/bskychatbot/node_modules/@atcute/client/dist/rpc.js:82:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Bot.sendMessages (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1016:26)
      at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:61:3) {
    status: 429,
    kind: 'RateLimitExceeded',
    description: 'Rate Limit Exceeded',
    headers: {
      'access-control-allow-origin': '*',
      'cache-control': 'private',
      'content-length': '61',
      'content-type': 'application/json; charset=utf-8',
      date: 'Sat, 26 Oct 2024 04:06:11 GMT',
      etag: 'W/"3d-egyFOcXCrKQFzoI7522/4+PpxIk"',
      'keep-alive': 'timeout=90',
      'ratelimit-limit': '3000',
      'ratelimit-policy': '3000;w=300',
      'ratelimit-remaining': '2994',
      'ratelimit-reset': '1729915865',
      'strict-transport-security': 'max-age=63072000',
      vary: 'Authorization, Accept-Encoding',
      'x-powered-by': 'Express'
    },
    [cause]: undefined
  }
}
```

**Comment by futurGH** [comment]
Weird, I'll have to see if I can reproduce.

**Comment by futurGH** [comment]
Can you give beta.1 a shot? Apologies, this is tough to pin down.

**Comment by futurGH** [comment]
Fix is published in 0.3.7, let me know if you continue to run into this.

**Comment by ledlamp** [comment]
Happened again
```
2024-11-04T20:52:52.712Z,did:plc:icwasmy7mggrjaw4k5yam2nt,luizzeroxis,luizzeroxis.bsky.social,that before might not happen because you could assume people didnt see the thin
g at all at least
Error: Failed to send messages.
    at file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1017:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.sendMessages (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1014:26)
    at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:94:3) {
  [cause]: XRPCError: RateLimitExceeded > Rate Limit Exceeded
      at RateLimitedAgent.request (file:///home/ubuntu/bskychatbot/node_modules/@atcute/client/dist/rpc.js:82:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Bot.sendMessages (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:1014:26)
      at async Bot.<anonymous> (file:///home/ubuntu/bskychatbot/index.mjs:94:3) {
    status: 429,
    kind: 'RateLimitExceeded',
    description: 'Rate Limit Exceeded',
    headers: {
      'access-control-allow-origin': '*',
      'cache-control': 'private',
      'content-length': '61',
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 04 Nov 2024 20:52:56 GMT',
      etag: 'W/"3d-egyFOcXCrKQFzoI7522/4+PpxIk"',
      'keep-alive': 'timeout=90',
      'ratelimit-limit': '3000',
      'ratelimit-policy': '3000;w=300',
      'ratelimit-remaining': '2950',
      'ratelimit-reset': '1730753700',
      'strict-transport-security': 'max-age=63072000',
      vary: 'Authorization, Accept-Encoding',
      'x-powered-by': 'Express'
    },
    [cause]: undefined
  }
}
Error: Failed to send message.
    at file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:968:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Bot.sendMessage (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:956:26) {
  [cause]: XRPCError: RateLimitExceeded > Rate Limit Exceeded
      at RateLimitedAgent.request (file:///home/ubuntu/bskychatbot/node_modules/@atcute/client/dist/rpc.js:82:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Bot.sendMessage (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:956:26) {
    status: 429,
    kind: 'RateLimitExceeded',
    description: 'Rate Limit Exceeded',
    headers: {
      'access-control-allow-origin': '*',
      'cache-control': 'private',
      'content-length': '61',
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 04 Nov 2024 20:52:56 GMT',
      etag: 'W/"3d-egyFOcXCrKQFzoI7522/4+PpxIk"',
      'keep-alive': 'timeout=90',
      'ratelimit-limit': '3000',
      'ratelimit-policy': '3000;w=300',
      'ratelimit-remaining': '2949',
      'ratelimit-reset': '1730753700',
      'strict-transport-security': 'max-age=63072000',
      vary: 'Authorization, Accept-Encoding',
      'x-powered-by': 'Express'
    },
    [cause]: undefined
  }
}
```
Version was 0.3.7-beta.1, but it's the same right?

**Comment by futurGH** [comment]
Weird, the headers indicate you've still got 2950 requests remaining. What's the other process running on your server (i.e. is it also running @skyware bot? Is it only using chat endpoints or others as well?)

**Comment by ledlamp** [comment]
it's running in my house so the other client would be me using the bluesky chat

**Comment by ledlamp** [comment]
Actually, I'm on a different network with different IP so it must be just the bot but it still happens.

I'm using .sendMessages() with more than a dozen people, could it be that this rate limit is for the individual messages and not the HTTP requests? https://gitea.moe/lamp/bluesky-groupchat-bot/src/branch/master/index.mjs#L97

**Comment by futurGH** [comment]
That's a timestamp, not a length of time. Really not sure though, my best guess is that the chat service has its own rate limits that aren't actually being exposed — will need to ask about it.

**Comment by wykhuh** [comment]
The  @atproto/api package says AtpAgent identifier/password login is being deprecated. They want people to switch to OAuth.   https://www.npmjs.com/package/@atproto/api

Someone posted that they had the rate limit issue with using AtpAgent login, but things are ok when switching to OAuth and JWT.
https://github.com/bluesky-social/atproto/discussions/2818

Is this related to the rate limit bug with the skyware Bot?

**Comment by ledlamp** [comment]
Well their response has ratelimit limit of 100 while here you can see it's 3000. And seems they're talking about createSession request but they didn't say. In that case it should not affect anything unless you need to restart bot more than 100 times in a day.

There must be some unspecified rate limits on chat and I don't know how it works. My bot has been getting 429 for over 17 hours now, just trying to sendMessages() every 10 seconds.
