### ISSUE TITLE
Facet thing makes invalid payload if an invalid handle is followed by any handle

### ISSUE THREAD

**Issue by ledlamp** [skyware-js/bot#19]
```js
var conversationId = (await bot.listConversations()).conversations.find(c => c.members.some(m => m.handle == "lamp.bsky.social")).id;

bot.sendMessage({conversationId, text: "@missing.invalid"}).catch(console.error); // ok

bot.sendMessage({conversationId, text: "@lamp.bsky.social @missing.invalid"}).catch(console.error); // ok

bot.sendMessage({conversationId, text: "@missing.invalid @lamp.bsky.social"}).catch(console.error); // error
```

```js
//vscode debug console has its own bugs and wont copy value
bot.sendMessage({conversationId, text: "@missing.invalid @lamp.bsky.social"}).catch(e => console.error(e.cause.stack))
```

```
XRPCError: InvalidRequest > Input/message/facets/0/features/0/did must be a valid did
    at RateLimitedAgent.request (file:///home/ubuntu/bskychatbot/node_modules/@atcute/client/dist/rpc.js:82:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Bot.sendMessage (file:///home/ubuntu/bskychatbot/node_modules/@skyware/bot/dist/bot/Bot.js:956:26)
 ```

**Comment by futurGH** [comment]
Good catch, thanks!
