### ISSUE TITLE
Problem using typescript

### ISSUE THREAD

**Issue by Cristuker** [skyware-js/bot#6]
I have this source code

```js
import { AtpAgent, AtpSessionData } from "@atproto/api";
import { getSession, saveSession } from "../redis";
import { Bot } from "@skyware/bot";
import "dotenv/config";

export const generateAgentAndBot = async (): Promise<[AtpAgent,Bot]> => {
  const bot = new Bot();
  const agent = new AtpAgent({
    service: "https://bsky.social",
    persistSession: async (evt: string, session: AtpSessionData | undefined) => {
      await saveSession(JSON.stringify(session));
      console.log('Persist session');
    }
  });

  const session = await getSession();

  if (session) {
    console.log("Resume session");
    await agent.resumeSession(JSON.parse(session));
    await bot.resumeSession(JSON.parse(session))
    return [agent, bot];
  }

  const  { data } = await agent.login({
    identifier: String(process.env.IDENTIFIER),
    password: String(process.env.PASSWORD),
  });
  await bot.resumeSession({
    refreshJwt: data.refreshJwt,
    accessJwt: data.accessJwt,
    handle: data.handle,
    did: data.did,
    email: data.email,
    emailConfirmed: data.emailConfirmed,
    emailAuthFactor: data.emailAuthFactor,
    active: !!data.active,
    status: data.status
  })

  console.log("Create a new Session");

  return [agent, bot];
};

```

and when I run I receive this error on terminal

```bash

/home/cristian/github/save-to-later/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/cristian/github/save-to-later/node_modules/@skyware/bot/dist/index.js from /home/cristian/github/save-to-later/src/config/agentProxy.ts not supported.
Instead change the require of index.js in /home/cristian/github/save-to-later/src/config/agentProxy.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/home/cristian/github/save-to-later/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/cristian/github/save-to-later/src/config/agentProxy.ts:15:15)
    at m._compile (/home/cristian/github/save-to-later/node_modules/ts-node/dist/index.js:857:29) {
  code: 'ERR_REQUIRE_ESM'
}
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by futurGH** [comment]
As the error says, the library only supports ESM. You'll need to set up your tsconfig accordingly.

You can also access `bot.agent` instead of initializing your own.

**Comment by Cristuker** [comment]
> As the error says, the library only supports ESM. You'll need to set up your tsconfig accordingly.
> 
> You can also access `bot.agent` instead of initializing your own.

I will do this

**Comment by futurGH** [comment]
Try `"module": "esnext"`. You can look up TypeScript configs for Node with ESM — this isn't really relevant to the library, so I'm going to close this issue.

**Comment by Cristuker** [comment]
I'm trying to use this with TS and I'm find some problems. So yes it's really relevant. I don't have this kind of problem with others lib

**Comment by Cristuker** [comment]
> instead of initializing your own.

I want but I can't pass 

```
persistSession: async (evt: string, session: AtpSessionData | undefined) => {
      await saveSession(JSON.stringify(session));
      console.log('Persist session');
    }
```

to bot agent. I need do this to save my session and avoid break rate limit

**Comment by futurGH** [comment]
You can persist the result of `Bot.login()` and pass that to `resumeSession` — will add that as an option though.
